### ISSUE TITLE
ablity to open the diff in an external diff program

### ISSUE THREAD

**Issue by miketamis** [jakesankey/git-history#10]
Would love the ablity to open the current file and an older in an external difftool, ie
`Git History: File history DiffTool` (idk im not really good at names)
then you select the version you want (like with `Git History: Show File History`) 
then it opens it in your difftool of choice set it settings with ie `meld {current} {old}`

**Comment by jakesankey** [comment]
I have this feature on my to-do list. It may initially just diff inside of atom but I will keep the difftool integration in mind.
