### ISSUE TITLE
Highlight changes

### ISSUE THREAD

**Issue by rthijssen** [jakesankey/git-history#16]
I'm sure if this has been suggested before but it would be great if the current file could show what has changed since the commit that is shown. This would make code reviews a lot easier ;)

**Comment by webanck** [comment]
I support this request !
You made multiple good packages in this direction already, please continue to add to the "git colorify the world with my commits and diffs"  ;)

**Comment by jakesankey** [comment]
I have looked into adding this in the future.. A previous release included a rudimentary implementation of diffing, however, I removed it (temporarily?) in favor of other plugins that solely handle diff visualization.

**Comment by rthijssen** [comment]
So I've looked around for plugins that do this. One of the plugins I found is [Atom compare files](https://github.com/floydpink/atom-compare-files). But none of them seem to support diffing commits.

I don't know what the best approach is to implement this feature, but I like what you have and adding a similar diffing view to what for example [Kaleidoscope](http://www.kaleidoscopeapp.com/static/img/screenshots/Text_Blocks.png) has would be pretty amazing.

I'm fully aware of what I'm asking for, and realize this is not a simple feature. But if you have an idea on how to do this I'm more than happy to help you out (with the limited amount of time I have) if necessary.

**Comment by rthijssen** [comment]
Not sure if useful, but maybe [Mergely](https://github.com/wickedest/Mergely) could make implementing this feature a whole lot easier?

**Comment by jakesankey** [comment]
I released a new version today that includes an initial implementation of diffing. In the git-history settings, just enable 'Show Diff' if it isn't already enabled. it will show you what has changed in your current version of the file vs. the commit you selected.

**Comment by rthijssen** [comment]
Awesome, thanks heaps for implementing this so quickly.

**Comment by webanck** [comment]
Yeah, this is super awesome!

**Comment by jakesankey** [comment]
Great! Thanks for the feedback. Enjoy! :+1:
