### ISSUE TITLE
Always get "Could not retrieve history for xxx"

### ISSUE THREAD

**Issue by kbsizer** [jakesankey/git-history#18]
Regardless of the active file or commit history item selected, this is what happens to me:

1) Ctrl-Alt-H    --> get list of commits
2) select a commit from the list
3) Get message "Could not retrieve history for xxxxx"

Otherwise, Atom/Git seems to be setup correctly:  I see files appropriately highlighted (up-to-date, uncommitted change, etc.)

Not being very familiar with Atom, I'm not sure what I might to do help debug, but I'd be happy to try something and report back with config info, stack traces, etc.
Thanks,
Ken

**Comment by ChowSinWon** [comment]
Same problem here.

**Comment by jakesankey** [comment]
I'm sorry. I'm not able to reproduce the issue... You are running the latest atom and version of the package? You have a net connection?

**Comment by kbsizer** [comment]
Yes, everything up-to-date. Such a bummer; man, would that be handy!

**Comment by jakesankey** [comment]
It is indeed handy. Any other info you can provide? 
Do you have multiple projects open in the same workspace? 
Has the given repo been pushed to a remote before or is it a new repo? 
Do you have git installed globally (can you execute 'git' at cmd line?)

**Comment by kbsizer** [comment]
I'm usually living/working in git bash. Do most everything from command
line, including launching Atom. Atom clearly knows that I'm in a
git-managed folder, because files all have appropriate git status
highlighting. Your plugin shows me the complete and correct commit history,
so it is at least partially working. My OS is Windows 7. Is there some
command or key sequence that would dump out a system status or
configuration that might help you?

**Comment by jakesankey** [comment]
Not that I am aware of.. I wish it was causing an exception as that might shed some light on this issue. You could modify the code and put some logging in there. All the plugin is doing is executing global 'git log/show'. There could be a Json issue or something that is specific to Windows, but I am on a Mac. I am bit helpless at this point until I can get my hands on a PC. Do you see the issue with all projects or is it a specific one?

**Comment by kbsizer** [comment]
"Could not retrieve history for init.pp"

"Could not retrieve history for input.json"

Seems to be consistent anywhere I go.

**Comment by eugeniussoftdev** [comment]
I have the same problem. I've just switched Sublime to Atom and installed git-history plugin. I do Ctrl+Alt+H it shows me all my commits to selected file but when I click I says "Could not retrieve history for 'my file'". I'm on Ubuntu. Can you help?

**Comment by saidmoya12** [comment]
Same issue on windows 10

**Comment by macdonaldtomw** [comment]
Same issue with me... could it be because my repo is on GitLab instead of GitHub?

**Comment by LHozzan** [comment]
Same problem for me too.
![Snímka obrazovky z 2019-06-18 16-15-19](https://user-images.githubusercontent.com/24796361/59691979-4eac5a80-91e4-11e9-8812-0d8ec8de8029.png)
Using GitHub.
If you need any aditional information, please, let me know.
