### ISSUE TITLE
Uncaught SyntaxErrors on run

### ISSUE THREAD

**Issue by SamuelMS** [jakesankey/git-history#2]
Just installed the package because it sounded remarkably useful. Unfortunately, it threw these errors as soon as I hit "ctrl-alt-o" to go through a file's history (although a dropdown appears at the top of the window stating that file history is being loaded). I'm running Windows 7 SP1 with Atom 0.141.0.

```
Uncaught SyntaxError: Unexpected token F VM559 /c:/Users/<name>/.atom/packages/git-history/lib/git-history-view.coffee:44stdout VM559 /c:/Users/<name>/.atom/packages/git-history/lib/git-history-view.coffee:44(anonymous function) d:\Utilities\Atom\resources\app\src\buffered-process.js:92emit events.js:107readableAddChunk _stream_readable.js:162Readable.push _stream_readable.js:125onread net.js:514

Uncaught SyntaxError: Unexpected token F VM559 /c:/Users/<name>/.atom/packages/git-history/lib/git-history-view.coffee:44stdout VM559 /c:/Users/<name>/.atom/packages/git-history/lib/git-history-view.coffee:44(anonymous function) d:\Utilities\Atom\resources\app\src\buffered-process.js:103emit events.js:129(anonymous function) net.js:461

Uncaught SyntaxError: Unexpected token F VM559 /c:/Users/<name>/.atom/packages/git-history/lib/git-history-view.coffee:44

Uncaught SyntaxError: Unexpected token F VM559 /c:/Users/<name>/.atom/packages/git-history/lib/git-history-view.coffee:44
```

**Comment by despairblue** [comment]
Seems to happen if the commit messages contain double quotes: 

```
{"hash": "5459f0e","author": "Danny Arnold","relativeDate": "3 weeks ago","fullDate": "2014-11-12","message": "Revert "Fix smth""},
{"hash": "0059579","author": "Danny Arnold","relativeDate": "3 weeks ago","fullDate": "2014-11-12","message": "Fix smth"},
```

**Comment by jakesankey** [comment]
Yes, I believe you're correct. I am not handling the double quote scenario. Feel free to submit a pull request. Otherwise, I will take a look when I get some time. Thanks for the info.

**Comment by ChowSinWon** [comment]
pull request by @silvenon reintroduced this issue. so after all we do need a fix like the one i did before...

**Comment by silvenon** [comment]
I didn't know that was there for a reason, sorry. I'll see what can be done without resorting to `%f` again.

**Comment by ChowSinWon** [comment]
you could look at my pull request #4, where i kind of solved it (in two different ways)...
it was closed due to the %f solution.

**Comment by silvenon** [comment]
This only accounts for double quotes, as far as I see. But wouldn't a curly brace also screw it up? It seems like there is a ton of things that can go wrong because there can be thousands of commit messages written in different styles with different annotations. I think `%f` is the safest solution for now…

**Comment by ChowSinWon** [comment]
yes, you are probably right :)

**Comment by silvenon** [comment]
Ok, fixed.
