### ISSUE TITLE
Does not work with preview tabs

### ISSUE THREAD

**Issue by rumpelsepp** [jakesankey/git-history#25]
When using atoms new preview tabs, git-history does not work.

**Comment by jakesankey** [comment]
@rumpelsepp - thanks for the heads-up. I will look into this when I get a chance.

**Comment by jakesankey** [comment]
@rumpelsepp - Perhaps there was a glitch in an earlier version of the preview tabs functionality but it seems to work just fine for me in atom 1.0.7 and git-history 3.0.1

**Comment by rumpelsepp** [comment]
:+1:
