### ISSUE TITLE
Commits made before renaming a file are not listed in history

### ISSUE THREAD

**Issue by misko321** [jakesankey/git-history#27]
If you move or rename a file (even with `git mv`), git-history shows only those commits that were made after the change. Unless it's done by purpose, I think it would be more useful to show all versions of the file.

It seems that git's `--follow` option does the job:
 [https://stackoverflow.com/questions/3701404/list-all-commits-for-a-specific-file](https://stackoverflow.com/questions/3701404/list-all-commits-for-a-specific-file)

**Comment by jakesankey** [comment]
You are correct. This package does not utilize the --follow option.. There was really not a lot of thought behind this other than that nobody has asked for it. I will plan to put it in in the next release unless you would like to do it and submit a pull request before then.
