### ISSUE TITLE
Could Not Retrieve History

### ISSUE THREAD

**Issue by bernardodsanderson** [jakesankey/git-history#28]
<img width="568" alt="screen shot 2015-09-17 at 10 40 28 pm" src="https://cloud.githubusercontent.com/assets/5623786/9951536/36602a5e-5d8d-11e5-8cfc-27bbf7c91b23.png">

I'm running into an issue where I get the history of commits, but when I try selecting a commit I get the error above. Any way to find out more about what's going on?

**Comment by jakesankey** [comment]
is template.php tracked in your repo? Have you committed it before?

**Comment by bernardodsanderson** [comment]
Yep, it's tracked and it's been committed several times.

**Comment by jakesankey** [comment]
Ok, thanks. This issue has been reported, closed, and reopend :confounded: .. See issue #1 ... I will close this thread for now and use the other.
