### ISSUE TITLE
Package causes some atom features get stucked

### ISSUE THREAD

**Issue by jakubhruby** [jakesankey/git-history#8]
# Steps to reproduce
- install & enable package
- try to search a phrase in project
- try to show list of calls to deprecated methods
- disable package and try these steps again
# Expected results
- phrase is being searched and results are shown in the search tab
- tab with list of calls to deprecated methods opens
# Actual results
- phrase is being searched, but result window doesn't show any result
- tab with list of calls doesn't open
- after disabling package everything works as expected

I think the package obstructs atom somehow from refreshing tab or opening new one.
The bug does not appear after fresh install, you are suppose to use it for a while, maybe it is connected with some cache memory?
Ask me for more details.

**Comment by jakesankey** [comment]
I am unable to reproduce the issue you are seeing. Any additional information you can provide would be great.

**Comment by jakubhruby** [comment]
@jakesankey I will try to reproduce it. Now I'm running the package for a day w/o crash, so it may have been fixed by the last Atom release.

**Comment by jakesankey** [comment]
Please let me know and close out the issue if it is indeed resolved..

**Comment by jakubhruby** [comment]
I'm not able to reproduce this again, so I think it has been fixed with Atom 0.176 release. Closing.
