### ISSUE TITLE
Diff commit with HEAD

### ISSUE THREAD

**Issue by yriveiro** [jakesankey/git-history#9]
The only missing thing that I found in this package is the diff between the hash commit and the HEAD.

Would be nice if the inserted removed and updated parts were highlighted like gutter does or something similar.

**Comment by jakesankey** [comment]
displaying diff information in a meaningful way is something that is on my list for a future version.

**Comment by jakesankey** [comment]
There is a preliminary implementation now in the latest version of git-history. Under the git-history settings make sure to select that you want diff info shown. Note that there is still a lot of room for improvement but it does effectively show you the additions and subtractions between the given version and HEAD.
